version: '2'
services:
  roulette-app:
    image: roulette
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://roulette-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=roulette
      - JHIPSTER_CACHE_REDIS_SERVER=redis://roulette-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://roulette-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  roulette-mongodb:
    extends:
      file: mongodb.yml
      service: roulette-mongodb
  roulette-redis:
    extends:
      file: redis.yml
      service: roulette-redis
